import ObsidianFlames from '../lib/mock-images/pokemon-obsidian.jpg';

export const products = [
    {
        id: 1,
        category: 'Card Games',
        name: 'Catan',
        img: { url: ObsidianFlames },
        price: 29.99,
        type: 'Strategy',
        rrp: 35.0,
        description: 'A game of strategy and skill.',
        stock: {
            amount: 100,
            sold: 50,
            instock: 'In Stock',
            soldout: 'Out of Stock',
            preorder: 'Available for Preorder',
        },
        preorder: false,
    },
    {
        id: 2,
        category: 'Card Games',
        name: 'Uno',
        img: { url: ObsidianFlames },
        price: 9.99,
        type: 'Family',
        rrp: 12.0,
        description: 'A classic card game for the whole family.',
        stock: {
            amount: 200,
            sold: 150,
            instock: 'In Stock',
            soldout: 'Out of Stock',
            preorder: 'Available for Preorder',
        },
        preorder: true,
    },
    {
        id: 3,
        category: 'Miniatures',
        name: 'Warhammer 40k',
        img: { url: ObsidianFlames },
        price: 99.99,
        type: 'Wargame',
        rrp: 120.0,
        description: 'A popular miniatures game set in a dystopian future.',
        stock: {
            amount: 50,
            sold: 20,
            instock: 'In Stock',
            soldout: 'Out of Stock',
            preorder: 'Available for Preorder',
        },
        preorder: false,
    },
    {
        id: 4,
        category: 'RPG',
        name: 'Dungeons & Dragons',
        img: { url: ObsidianFlames },
        price: 49.99,
        type: 'Role-Playing',
        rrp: 55.0,
        description: "The world's most popular role-playing game.",
        stock: {
            amount: 150,
            sold: 120,
            instock: 'In Stock',
            soldout: 'Out of Stock',
            preorder: 'Available for Preorder',
        },
        preorder: true,
    },
];
