import ObsidianFlames from '../lib/mock-images/pokemon-obsidian.jpg';

export const products = [
    {
        id: 1,
        category: 'card games',
        game: 'pokemon',
        name: 'Pokemon Scarlet & Violet Obsidian Flames: Booster Pack (10 Cards)',
        img: ObsidianFlames,
        price: '3.99',
        type: 'pack',
        rrp: '4.29',
        stock: {
            amount: 20,
            sold: 15,
            instock: 'In Stock',
            soldout: 'sold out',
            preorder: 'preorder',
        },
    },
    {
        id: 2,
        category: 'card games',
        game: 'yugioh',
        name: 'Pokemon Scarlet & Violet Obsidian Flames: Booster Pack (10 Cards)',
        img: ObsidianFlames,
        price: '3.99',
        type: 'pack',
        rrp: '4.29',
        stock: {
            amount: 20,
            sold: 15,
            instock: 'In Stock',
            soldout: 'soldout',
            preorder: 'preorder',
        },
    },
    {
        id: 3,
        category: 'card games',
        game: 'pokemon',
        name: 'Pokemon Scarlet & Violet Obsidian Flames: Booster Pack (10 Cards)',
        img: ObsidianFlames,
        price: '3.99',
        type: 'pack',
        rrp: '4.29',
        stock: {
            amount: 20,
            sold: 15,
            instock: 'In Stock',
            soldout: 'soldout',
            preorder: 'preorder',
        },
    },
    {
        id: 5,
        category: 'card games',
        game: 'pokemon',
        name: 'Pokemon Scarlet & Violet Obsidian Flames: Booster Pack (10 Cards)',
        img: ObsidianFlames,
        price: '3.99',
        type: 'pack',
        rrp: '4.29',
        stock: {
            amount: 20,
            sold: 15,
            instock: 'In Stock',
            soldout: 'soldout',
            preorder: 'preorder',
        },
    },
    {
        id: 6,
        category: 'card games',
        game: 'pokemon',
        name: 'Pokemon Scarlet & Violet Obsidian Flames: Booster Pack (10 Cards)',
        img: ObsidianFlames,
        price: '3.99',
        type: 'pack',
        rrp: '4.29',
        stock: {
            amount: 20,
            sold: 15,
            instock: 'In Stock',
            soldout: 'soldout',
            preorder: 'preorder',
        },
    },
];
