export { Icon as Imperatus } from './logo';
export { Icon as RegisterIcon } from './register';
export { Icon as UserIcon } from './user';
export { Icon as BasketIcon } from './basket';
export { Icon as SearchIcon } from './search';
export { Icon as AdminIcon } from './admin-settings';
export { Icon as Cart } from './cart';
export { Icon as Delete } from './delete';
export { Icon as Heart } from './heart';
export { Icon as ClockThree } from './clock-three';
export { Icon as CreditCard } from './credit-card';
export { Icon as Van } from './van';
export { Icon as SignOut } from './sign-out';
export { Icon as Pie } from './pie';
export { Icon as SquareShapes } from './square-shapes';
export { Icon as AdminDivider } from './admin-divider';
export { Icon as Percent } from './percent';
export { Icon as Carousel } from './carousel';
export { Icon as Eye } from './eye';
export { Icon as Info } from './info';
export { Icon as CardGameIcon } from './card-document';
export { Icon as Promotion } from './promotion';
export { Icon as Stripe } from './stripe';
export { Icon as Visa} from './visa';
export { Icon as Mastercard} from './mastercard';
export { Icon as Discover } from './discover';
export { Icon as AmericanExpress} from './american-express';
export { Icon as Timer } from './time'
